name: contributor-takes-action
description: This is an action to assign yourself to an issue for a repo you are not a contributor to.
author: B Dolla Mon$ign
branding:
  icon: 'thumbs-up'
  color: 'white'
